var facts =["Banging your head against a wall burns 150 calories an hour.",
"In the UK, it is illegal to eat mince pies on Christmas Day!",
"Pteronophobia is the fear of being tickled by feathers!",
"When hippos are upset, their sweat turns red.",
"A flock of crows is known as a murder.",
"“Facebook Addiction Disorder” is a mental disorder identified by Psychologists.",
"The average woman uses her height in lipstick every 5 years.",
"29th May is officially “Put a Pillow on Your Fridge Day“.",
"Cherophobia is the fear of fun.",
"Human saliva has a boiling point three times that of regular water.",
"If you lift a kangaroo’s tail off the ground it can’t hop.",
"Bananas are curved because they grow towards the sun.",
"Billy goats urinate on their own heads to smell more attractive to females.",
"The person who invented the Frisbee was cremated and made into frisbees after he died!",
"During your lifetime, you will produce enough saliva to fill two swimming pools.",
"If Pinokio says “My Nose Will Grow Now”, it would cause a paradox. Details here.",
"Polar bears can eat as many as 86 penguins in a single sitting. (If they lived in the same place)",
"King Henry VIII slept with a gigantic axe beside him.",
"Movie trailers were originally shown after the movie, which is why they were called “trailers”.",
"An eagle can kill a young deer and fly away with it.",
"Heart attacks are more likely to happen on a Monday.",
"If you consistently fart for 6 years & 9 months, enough gas is produced to create the energy of an atomic bomb!",
"in 2015, more people were killed from injuries caused by taking a selfie than by shark attacks.",
"The top six foods that make your fart are beans, corn, bell peppers, cauliflower, cabbage and milk!",
"There is a species of spider called the Hobo Spider.","A lion’s roar can be heard from 5 miles away!",
"A toaster uses almost half as much energy as a full-sized oven.",
"A baby spider is called a spiderling.",
"You cannot snore and dream at the same time.",
"The following can be read forward and backwards: Do geese see God?",
"A baby octopus is about the size of a flea when it is born.",
"A sheep, a duck and a rooster were the first passengers in a hot air balloon.",
"In Uganda, 50% of the population is under 15 years of age.",
"Hitler’s mother considered abortion but the doctor persuaded her to keep the baby.",
"Arab women can initiate a divorce if their husbands don’t pour coffee for them.",
"Recycling one glass jar saves enough energy to watch TV for 3 hours.",
"Smearing a small amount of dog feces on an insect bite will relieve the itching and swelling.",
"Catfish are the only animals that naturally have an odd number of whiskers.",
"Facebook, Skype and Twitter are all banned in China.",
"95% of people text things they could never say in person.",
"The Titanic was the first ship to use the SOS signal.",
"In Poole, ‘Pound World’ went out of business because of a store across the road called ’99p Stores’, which was selling the same products but for just 1 pence cheaper!",
"About 8,000 Americans are injured by musical instruments each year.",
"The French language has seventeen different words for ‘surrender’.",
"Nearly three percent of the ice in Antarctic glaciers is penguin urine.",
"Bob Dylan’s real name is Robert Zimmerman.",
"A crocodile can’t poke its tongue out :p",
"Sea otters hold hands when they sleep so they don’t drift away from each other.",
"A small child could swim through the veins of a blue whale.",
"Bin Laden’s death was announced on 1st May 2011. Hitler’s death was announced on 1st May 1945.",
"J.K. Rowling chose the unusual name ‘Hermione’ so young girls wouldn’t be teased for being nerdy!",
"Hewlett-Packard’s name was decided in a coin toss.",
"The total number of steps in the Eiffel Tower are 1665.",
"The Pokémon Hitmonlee and Hitmonchan are based off of Bruce Lee and Jackie Chan.",
"An arctophile is a person who collects, or is very fond of teddy bears.",
"Pirates wore earrings because they believed it improved their eyesight.",
"Los Angeles’s full name is “El Pueblo de Nuestra Senora la Reina de los Angeles de Porciuncula.”",
"The Twitter bird actually has a name – Larry.",
"Octopuses have four pairs of arms.",
"In England, in the 1880’s, “Pants” was considered a dirty word.",
"It snowed in the Sahara desert for 30 minutes on the 18th February 1979.",
"Every human spent about half an hour as a single cell.",
"If you leave everything to the last minute… it will only take a minute.",
"Unlike many other big cats, snow leopards are not aggressive towards humans. There has never been a verified snow leopard attack on a human being.",
"The first alarm clock could only ring at 4am.",
"Birds don’t urinate.",
"Dying is illegal in the Houses of Parliaments – This has been voted as the most ridiculous law by the British citizens.",
"The most venomous jellyfish in the world is named the Irukandji and is smaller than your fingernail.",
"The 20th of March is known as Snowman Burning Day!",
"Slugs have 4 noses.",
"Panphobia is the fear of everything… which is a pretty unlucky phobia to have.",
"An apple, potato, and onion all taste the same if you eat them with your nose plugged.",
"The front paws of a cat are different from the back paws. They have five toes on the front but only four on the back.",
"A company in Taiwan makes dinnerware out of wheat, so you can eat your plate!",
"The average person walks the equivalent of twice around the world in a lifetime.",
"The Bible is the most shoplifted book in the world.",
"Marco Hort has the world record for fitting 264 straws in his mouth at once!",
"Mel Blanc – the voice of Bugs Bunny – was allergic to carrots.",
"California has issued 6 drivers licenses to people named Jesus Christ.",
"According to Genesis 1:20-22 the chicken came before the egg.",
"In the Caribbean there are oysters that can climb trees.",
"Worms eat their own poo.",
"Squirrels forget where they hide about half of their nuts.",
"Over 1000 birds a year die from smashing into windows.",
"The inventor of the Waffle Iron did not like waffles.",
"George W. Bush was once a cheerleader.",
"In total, there are 205 bones in the skeleton of a horse.",
"In 1895 Hampshire police handed out the first ever speeding ticket, fining a man for doing 6mph!",
"Each year, there are more than 40,000 toilet related injuries in the United States.",
"Strawberries can also be yellow, green or white. This also affects the taste and some have a similar taste to pineapples.",
"Mewtwo is a clone of the Pokémon Mew, yet it comes before Mew in the Pokédex.",
"Every year more than 2500 left-handed people are killed from using right-handed products.",
"Madonna suffers from garophobia which is the fear of thunder.",
"China has more English speakers than the United States.",
"Samuel L. Jackson requested to have a purple light saber in Star Wars in order for him to accept the part as Mace Windu.",
"Paraskavedekatriaphobia is the fear of Friday the 13th!",
"Kleenex tissues were originally used as filters in gas masks.",
"In 1998, Sony accidentally sold 700,000 camcorders that had the technology to see through people’s clothes. These cameras had special lenses that use infrared light, which allowed you to see through some types of clothing.",
"During your lifetime, you will spend around thirty-eight days brushing your teeth.",
"Ronald McDonald is “Donald McDonald” in Japan because it makes pronunciation easier for the Japanese. In Singapore he’s known as “Uncle McDonald”."
];

function pullFact(){
  return facts[Math.floor(Math.random()*facts.length)];
  // console.log(fact);
}

module.exports.facts = facts;
module.exports.pullFact = pullFact;

// ["i do not like mushrooms", "i do not like onions", "i do not like peppers", "i'm hungry", "yep yep", "I am going to make nachos for dinner tonight...", "this is a really long list", "i am tired", "there is too much to do","node node node"]
